---
swagger: '2.0'
info:
  version: 0.0.1
  title: Rialto Entity Resolver
securityDefinitions:
  key:
    type: apiKey
    in: header
    name: X-API-Key
paths:
  /person:
    get:
      produces:
        - text/plain
      parameters:
        - name: first_name
          required: false
          type: string
          in: query
          description: First name of the person
        - name: full_name
          required: false
          type: string
          in: query
          description: Full name of the person
        - name: last_name
          required: false
          type: string
          in: query
          description: Last name of the person
        - name: orcid
          required: false
          type: string
          in: query
          description: ORCID of the person
      security:
        - key: []
      operationId: findOrCreatePerson
      responses:
        200:
          description: returns a URI for the person in Rialto
          schema:
            type: string
            description: contains the actual URI
  /healthcheck:
    get:
      produces:
        - application/json
      operationId: healthCheck
      responses:
        200:
          description: The service is working properly
          schema:
            $ref: "#/definitions/HealthCheckResponse"
        503:
          description: The service is not working properly
          schema:
            $ref: "#/definitions/HealthCheckResponse"
definitions:
  HealthCheckResponse:
    type: object
    properties:
      status:
        type: string
        description: "The status of the service"
    example:
      status: "OK"
