version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/sul-dlss/rialto-entity-resolver
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: go get github.com/golang/dep/cmd/dep
      - run: dep ensure -vendor-only
      - run: go test -v ./...
      - run: GOOS=linux go build -o server cmd/server/main.go

  register_image:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/sul-dlss/rialto-entity-resolver
    steps:
      - setup_remote_docker:
          version: 18.05.0-ce
      - checkout
      - run:
          name: Build Image & Register Task
          command: |
            docker build -t suldlss/rialto-entity-resolver:latest .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push suldlss/rialto-entity-resolver:latest

workflows:
  version: 2

  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
  
  register_image:
    jobs:
      - register_image:
          filters:
            branches:
              only: master

