version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:latest
    working_directory: /go/src/github.com/sul-dlss/rialto-entity-resolver
    steps:
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: go get github.com/golang/dep/cmd/dep
      - run: dep ensure -vendor-only
      - run: go test -v ./...
      - run: GOOS=linux go build -o server cmd/server/main.go
